"""initial_schema

Revision ID: 688f4d73a107
Revises: 
Create Date: 2026-04-04 15:44:47.057116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '688f4d73a107'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('secrets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lokam_call_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=True),
    sa.Column('rooftop_name', sa.String(length=150), nullable=True),
    sa.Column('campaign_name', sa.String(length=150), nullable=True),
    sa.Column('call_status', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('call_date', sa.Date(), nullable=False),
    sa.Column('nps_score', sa.Integer(), nullable=True),
    sa.Column('call_summary', sa.Text(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('positive_mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detractors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_incomplete_call', sa.Boolean(), nullable=True),
    sa.Column('incomplete_reason', sa.Text(), nullable=True),
    sa.Column('is_dnc_request', sa.Boolean(), nullable=True),
    sa.Column('escalation_needed', sa.Boolean(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('formatted_transcript', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('service_record_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('call_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_name_masked', sa.String(length=100), nullable=True),
    sa.Column('customer_phone_masked', sa.String(length=20), nullable=True),
    sa.Column('source_env', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lokam_call_id')
    )
    op.create_index('idx_raw_calls_call_date', 'raw_calls', ['call_date'], unique=False)
    op.create_index('idx_raw_calls_lokam_call_id', 'raw_calls', ['lokam_call_id'], unique=False)
    op.create_index('idx_raw_calls_source_env', 'raw_calls', ['source_env'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('evals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('call_status', sa.String(length=20), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('formatted_transcript', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('service_record_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formatted_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gt_call_summary', sa.Text(), nullable=True),
    sa.Column('gt_nps_score', sa.Integer(), nullable=True),
    sa.Column('gt_overall_feedback', sa.Text(), nullable=True),
    sa.Column('gt_positive_mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gt_detractors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gt_is_incomplete_call', sa.Boolean(), nullable=True),
    sa.Column('gt_incomplete_reason', sa.Text(), nullable=True),
    sa.Column('gt_is_dnc_request', sa.Boolean(), nullable=True),
    sa.Column('gt_escalation_needed', sa.Boolean(), nullable=True),
    sa.Column('scenario_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scenario_tags_str', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('eval_status', sa.String(length=20), nullable=False),
    sa.Column('has_corrections', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['raw_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evals_assigned_to', 'evals', ['assigned_to'], unique=False)
    op.create_index('idx_evals_call_id', 'evals', ['call_id'], unique=False)
    op.create_index('idx_evals_completed_at', 'evals', ['completed_at'], unique=False)
    op.create_index('idx_evals_eval_status', 'evals', ['eval_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_evals_eval_status', table_name='evals')
    op.drop_index('idx_evals_completed_at', table_name='evals')
    op.drop_index('idx_evals_call_id', table_name='evals')
    op.drop_index('idx_evals_assigned_to', table_name='evals')
    op.drop_table('evals')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_raw_calls_source_env', table_name='raw_calls')
    op.drop_index('idx_raw_calls_lokam_call_id', table_name='raw_calls')
    op.drop_index('idx_raw_calls_call_date', table_name='raw_calls')
    op.drop_table('raw_calls')
    op.drop_table('env_configs')
    # ### end Alembic commands ###
